### ISSUE TITLE
java.lang.NoSuchMethodException In org.cloudfoundry.router.ClientCertificateMapperAutoConfiguration

### ISSUE THREAD

**Issue by MouamleH** [cloudfoundry/java-buildpack-client-certificate-mapper#4]
When I deploy my code to cf it shows me this error message

```java
   org.springframework.cglib.core.CodeGenerationException: java.lang.NoSuchMethodException-->org.cloudfoundry.router.ClientCertificateMapperAutoConfiguration$$EnhancerBySpringCGLIB$$7ac26b9c.CGLIB$SET_THREAD_CALLBACKS([Lorg.springframework.cglib.proxy.Callback;)
   	at org.springframework.cglib.proxy.Enhancer$EnhancerFactoryData.<init>(Enhancer.java:510) ~[app/:na]
   	at org.springframework.cglib.proxy.Enhancer.wrapCachedClass(Enhancer.java:803) ~[app/:na]
   	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:111) ~[app/:na]
   	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108) ~[app/:na]
   	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) ~[app/:na]
   	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_232]
   	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) ~[app/:na]
   	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) ~[app/:na]
   	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134) ~[app/:na]
   	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319) ~[app/:na]
   	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:569) ~[app/:na]
   	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:416) ~[app/:na]
   	at org.springframework.context.annotation.ConfigurationClassEnhancer.createClass(ConfigurationClassEnhancer.java:137) ~[app/:na]
   	at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:109) ~[app/:na]
   	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:429) ~[app/:na]
   	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:263) ~[app/:na]
   	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286) ~[app/:na]
   	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:130) ~[app/:na]
   	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706) ~[app/:na]
   	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[app/:na]
   	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[app/:na]
   	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[app/:na]
   	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[app/:na]
   	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[app/:na]
   	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) [app/:na]
   	at APP_PACKAGE.APP_NAME.main(APP_NAME.java:52) [app/:na]
   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_232]
   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_232]
   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_232]
   	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_232]
   	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [app/:na]
   Caused by: java.lang.NoSuchMethodException: org.cloudfoundry.router.ClientCertificateMapperAutoConfiguration$$EnhancerBySpringCGLIB$$7ac26b9c.CGLIB$SET_THREAD_CALLBACKS([Lorg.springframework.cglib.proxy.Callback;)
   	at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[na:1.8.0_232]
   	at org.springframework.cglib.proxy.Enhancer.getCallbacksSetter(Enhancer.java:909) ~[app/:na]
   	at org.springframework.cglib.proxy.Enhancer.access$000(Enhancer.java:93) ~[app/:na]
   	at org.springframework.cglib.proxy.Enhancer$EnhancerFactoryData.<init>(Enhancer.java:499) ~[app/:na]
   	... 30 common frames omitted
   Exit status 0
```

**I traced down the issue and it googled the class** `ClientCertificateMapperAutoConfiguration` and I found it in this repo 

So upon further digging, I found out that the class `org.springframework.cglib.proxy.Enhancer` is calling `org.cloudfoundry.router.ClientCertificateMapperAutoConfiguration$$EnhancerBySpringCGLIB$$7ac26b9c.CGLIB$SET_THREAD_CALLBACKS([Lorg.springframework.cglib.proxy.Callback;)`

But it can't find it
![image](https://user-images.githubusercontent.com/31666226/72671637-5ffd6400-3a5e-11ea-955f-5d23c5c88555.png)

I looked for older versions of the class in this repo and the method is nowhere to be found.

**Comment by MouamleH** [comment]
Nvm fixed it by removing spring dev-tools from the dependencies
